def above_below(array, number):
    '''
    :param list array: array of numbers provided by user
    :param int number: value to be compared against array to count how many
                   array items are above and below it
    '''

    nums_above = 0
    nums_below = 0
    for i in array:
        # Assumed that array elements equal to input number are ignored
        if i > number:
            nums_above += 1
        if i < number:
            nums_below += 1

    print("above: ", nums_above, "below: ", nums_below)


def process_input():
    '''
    :return: list lst: array of integer values generated by user
    :return: int compare_to_number: integer value provided by user to compare array to
    '''

    try:
        lst = []
        input_list_size = int(input("Please provide array size: "))
        if input_list_size < 1:
            print("Array size must be an integer greater than zero")
            process_input()
        # Ask for array values one at a time
        for i in range(0, input_list_size):
            lst.append(int(input("input array value: ")))

        compare_to_number = (int(input("Please provide number to evaluate above/below with: ")))

        return lst, compare_to_number

    except:
        print("Please ensure array size, array values, and compare number are all integer values!")
        process_input()


def main():
    num_list, compare_num = process_input()
    above_below(num_list, compare_num)


if __name__ == "__main__":
    main()
